language: node_js
branches:
  only:
    - master
node_js:
  - "8"
cache:
  directories:
    - "node_modules"
install:
  - npm i npminstall && npminstall
  - npm install -g codecov
script:
  - npm run ci
